[package]
name = "ballast-core"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
barter-instrument.workspace = true
rust_decimal.workspace = true
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true
